; Polskie teksty szablonu instalatora Tauri (Tauri nie ma własnego tłumaczenia).
LangString addOrReinstall ${LANG_POLISH} "Dodaj lub zainstaluj ponownie"
LangString alreadyInstalled ${LANG_POLISH} "Już zainstalowano"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowana. Wybierz, co chcesz zrobić, i kliknij Dalej."
LangString appRunning ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiona. Zamknij grę i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "${PRODUCTNAME} jest uruchomiona.$\nKliknij OK, żeby ją zamknąć (postęp zapisuje się na bieżąco)."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz, co zrobić z zainstalowaną grą."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (instalacja starszej wersji bez odinstalowania jest wyłączona)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć ${PRODUCTNAME}. Zamknij grę i spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Zainstalowana jest już nowsza wersja ${PRODUCTNAME}. Instalowanie starszej nie jest zalecane; jeśli naprawdę jej potrzebujesz, najpierw odinstaluj obecną. Wybierz, co chcesz zrobić, i kliknij Dalej."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "Na komputerze jest zainstalowana $R4 wersja ${PRODUCTNAME}. Zalecamy odinstalowanie jej przed instalacją. Wybierz, co chcesz zrobić, i kliknij Dalej."
LangString silentDowngrades ${LANG_POLISH} "Ten instalator nie instaluje starszej wersji w trybie cichym. Uruchom go normalnie, z oknem kreatora.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie udało się odinstalować."
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2, a bez niego gra nie działa. Uruchom instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Błąd: nie udało się pobrać WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pobrano instalator WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie instalatora WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Błąd: instalacja WebView2 zakończyła się kodem $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Zainstalowano WebView2"
LangString deleteAppData ${LANG_POLISH} "Usuń też zapis gry i dane aplikacji"
